name: 构建并发布Sekiro

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*' # 当推送带v前缀的标签时触发，例如v1.0.0
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: 构建项目
      run: mvn -B clean package --file pom.xml
      
    - name: 获取版本号
      id: get_version
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION=$(date +'%Y%m%d%H%M%S')
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      
    - name: 压缩构建文件
      run: |
        mkdir release_files
        cp target/sekiro-open-0.0.1.jar release_files/
        cp -r target/sekiro-open-demo release_files/
        cd release_files
        zip -r ../sekiro-${{ env.VERSION }}.zip ./*
      
    - name: 上传构建制品
      uses: actions/upload-artifact@v4
      with:
        name: sekiro-${{ env.VERSION }}
        path: sekiro-${{ env.VERSION }}.zip
        
    - name: 创建Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          sekiro-${{ env.VERSION }}.zip
          target/sekiro-open-0.0.1.jar
        name: Sekiro 发布 ${{ env.VERSION }}
        body: |
          # Sekiro 版本 ${{ env.VERSION }}
          
          ## 启动方式
          ```
          java -jar sekiro-open-0.0.1.jar --sekiro.port=端口号 --sekiro.strict.bindClientCheck=true|false
          ```
          
          ## 配置说明
          - sekiro.port: 服务监听端口，默认为5612
          - sekiro.strict.bindClientCheck: 严格绑定客户端检查，设置为true或false
      
    - name: 更新依赖图
      uses: advanced-security/maven-dependency-submission-action@v3 